version: "3.6"

services:
  zabbix-proxy-sqlite3:
    image: zabbix/zabbix-proxy-sqlite3:alpine-5.4.12
    container_name: zabbix_proxy
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 10051:10051
    environment:
      - ZBX_PROXYMODE=0
      - ZBX_HOSTNAME=zbbx-proxy
      - ZBX_SERVER_HOST=x.x.x.x
      - ZBX_SERVER_PORT=10051
      - ZBX_DEBUGLEVEL=3


  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-5.4.12
    container_name: zabbix_agent2
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 10050:10050
    environment:
      - ZBX_HOSTNAME=zbbx-agent2
      - ZBX_SERVER_HOST=localhost
      - ZBX_DEBUGLEVEL=3
      - ZBX_ACTIVE_ALLOW=0
