---
- name: Instalar pacote Zabbix Agent
  hosts: zabbix
  become: true

  tasks:
    - name: Verificar se o pacote RPM já existe
      stat:
        path: /tmp/zabbix-agent2.rpm
      register: rpm_file

    - name: Baixar pacote RPM
      get_url:
        url: https://repo.zabbix.com/zabbix/6.4/rhel/7/x86_64/zabbix-agent2-6.4.2-release1.el7.x86_64.rpm
        dest: /tmp/zabbix-agent2.rpm
        validate_certs: false
      when: not rpm_file.stat.exists

    - name: Instalar pacote RPM
      command: yum -y --nogpgcheck localinstall /tmp/zabbix-agent2.rpm
      args:
        warn: no

    - name: Reiniciar serviço Zabbix Agent
      service:
        name: zabbix-agent2
        state: restarted
